name: Daily IPO Notifier
on:
  schedule:
    - cron: '30 8 * * 1-5'  # 1:30 PM IST (8:00 AM UTC) Mon-Fri
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 python-dotenv

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

    - name: Verify installations
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run IPO Notifier
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
      run: |
        python script.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: notified-ipos
        path: notified_ipos.txt
        retention-days: 7

    - name: Download previous artifact
      uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: notified-ipos
        path: .