name: IPO Notifier

on:
  schedule:
    - cron: "30 8 * * 1-5"  # 1:30 PM IST (8:00 AM UTC) Mon-Fri
  workflow_dispatch:

jobs:
  notify_ipos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: notified_ipos
          path: ./
        continue-on-error: true

      - name: Debug artifact
        run: |
          if [ -f notified_ipos.txt ]; then
            echo "Artifact contents:"
            cat notified_ipos.txt
          else
            echo "No artifact found"
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 python-dotenv

      - name: Install GeckoDriver
        run: |
          GECKODRIVER_VERSION=v0.35.0
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Run IPO Notifier
        env:
          SMTP_USER: ${{ secrets.GMAIL_USER }}
          SMTP_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
        run: |
          python script.py

      - name: Ensure artifact exists
        run: |
          if [ ! -f notified_ipos.txt ]; then
            touch notified_ipos.txt
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notified_ipos
          path: notified_ipos.txt