name: Daily IPO Notifier
on:
  schedule:
    - cron: '30 8 * * 1-5'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libxml2-dev libxslt-dev libssl-dev zlib1g-dev gcc
        sudo apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2

    - name: Install latest Firefox
      run: |
        sudo apt-get install -y firefox
        firefox --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 python-dotenv

    - name: Cache GeckoDriver
      uses: actions/cache@v3
      with:
        path: ~/.cache/geckodriver
        key: geckodriver

    - name: Install GeckoDriver
      run: |
        mkdir -p ~/.cache/geckodriver
        wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
        tar -xzf geckodriver-v0.35.0-linux64.tar.gz -C ~/.cache/geckodriver
        echo "$HOME/.cache/geckodriver" >> $GITHUB_PATH

    - name: Verify installations
      run: |
        firefox --version
        geckodriver --version

    - name: Run IPO Notifier
      env:
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
      run: |
        python script.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: notified-ipos
        path: notified_ipos.txt
        retention-days: 7

    - name: Download previous artifact
      uses: actions/download-artifact@v3
      continue-on-error: true
      with:
        name: notified-ipos
        path: .